title: Rom Hacks Studio
description:
theme: just-the-docs

url: https://AaghatIsLive.github.io/RomHacksStudio

aux_links:
  Discord: https://discord.gg/aaghat-s-server-965900074532081674

logo: "/ico_shuffle_2599.png"

favicon_ico: "/ico_shuffle_2599.png"


callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
    
