title: Rom Hacks Studio
description:
theme: just-the-docs

url: https://AaghatIsLive.github.io/RomHacksStudio

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
